mallchat:
  jwt:
    secret: dsfsdfsdfsdfsd
    # mysql配置
  mysql:
    db: mallchat
    ip: 127.0.0.1
    password: root
    port: 3306
    username: root
    # redis配置
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    # 微信公众号信息
  wx:
    # 接口配置里的aesKey值
    aesKey: sha1
    appId: appid
    callback: http://127.0.0.1:8080
    secret: 380bfc1c9147fdsf4sf07
    # 接口配置里的Token值
    token: sdfsf
# oss配置
oss:
  access-key: BEZ213
  bucketName: default
  enabled: true
  endpoint: http://localhost:9000
  secret-key: Ii4vCMIXuFe241dsfEZ8e7RXI2342342kV
  type: minio
